name=SimplexNoise
version=0.2.1
author=Jordan Shaw
maintainer=Jordan Shaw
sentence=A Simplex Noise library for Arduino
paragraph=Simplex Noise is a coherent noise algorithm that's faster than Perlin Noise. It's perfect for generating natural-looking motion and textures for servos, LEDs, and other physical outputs.
category=Data Processing
url=https://github.com/jshaw/SimplexNoise
architectures=*
includes=SimplexNoise.h,SimplexServo.h
depends=Servo,ESP32Servo,PWMServo
